    <!-- ******************************************************************************************* -->
<!-- breadcrumb Start-->
<div class="page-notification page-notification2">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="<?php echo BASE_URL; ?>">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="<?php echo BASE_URL; ?>tienda/contacto/vistacontacto">Contacto</a></li> 
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb End-->
        <!-- Hero Area End-->
        <!--?  Contact Area start  -->
        <section class="contact-section">
            <div class="container">
                
                <div class="row">
                    <div class="col-12">
                        <h2 class="contact-title">Contactenos</h2>
                    </div>
                    <div class="col-lg-8">
						
                            <input type="text"  class="single-input" name="asunto" id="asunto" placeholder="asunto">
                            <br>
                            <input type="text"  class="single-input" name="nombre" id="nombre" placeholder="nombre">
                            <br>
                            <input type="email" class="single-input" name="correo" id="correo" placeholder="e-mail">
                            <br>
                            <textarea class="single-textarea" name="comentario" id="comentario" cols="30" rows="10" placeholder="Mensaje"></textarea>
                            <br>
                            <button class="genric-btn primary circle arrow" id="enviar_correo_tienda">Enviar</button>
                        
                    </div>
                    
                </div>
            </div>
        </section>
<!-- /.login-box -->
<!-- ******************************************************************************************* -->