<div class="row">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header">
                <div class="row">
                <div class="col-md-3">
                <h3 class="card-title">Consulta Usuarios</h3>
                </div>
                <div class="col-md-3">
                    <button type="button" id="consultar" class="btn btn-primary">Consultar</button>
                </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table table-striped" id="reporte">
                    <thead>
                        <tr>
                        <th style="width: 10px">ID</th>
                        <th>Descripción</th>
                        <th>Usuario</th>
                        <th>Clave</th>
                        <th>Estado</th>
                        </tr>
                    </thead>
                    
                </table>
            </div>
            <!-- /.card-body -->
        </div>
            <!-- /.card -->
    </div>
    </div>
</div>
        