<!-- breadcrumb Start-->
        <div class="page-notification">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="<?php echo BASE_URL; ?>">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="<?php echo BASE_URL; ?>tienda/productos/vistaproductos">Tienda</a></li> 
                                <li class="breadcrumb-item"><a href="#">Carrito</a></li> 
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- breadcrumb End-->
                <div class="row" id="carrito_productos">
                    
                </div>
                <center>
                    <a href="<?php echo BASE_URL;?>productos/producto/vaciar_carrito" class="genric-btn danger e-large">Limpiar Carrito</a>
                    <a id="datos_carrito" href="<?php echo BASE_URL;?>tienda/factura/factura" target="_blank" class="genric-btn primary e-large">Finalizar Compra</a><br><br><br>
                    
                </center>