        <!-- breadcrumb Start-->
        <div class="page-notification">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="<?php echo BASE_URL; ?>">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="<?php echo BASE_URL; ?>tienda/productos/vistaproductos">Tienda</a></li> 
                                <li class="breadcrumb-item"><a href="#">Detalles del Producto</a></li> 
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb End-->

        <div class="row" id="detalles_prod">
            <p>hoasdf</p>
        </div>

