        <!-- breadcrumb Start-->
        <div class="page-notification">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="<?php echo BASE_URL; ?>">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="<?php echo BASE_URL; ?>tienda/productos/vistaproductos">Tienda</a></li> 
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="category-area">
            <div class="container">
                <div class="row">
                    <div class="col-xl-7 col-lg-8 col-md-10">
                    </div>
                </div>
                <div class="row">
                    <!--? Left content -->
                    <div class="col-xl-2 col-lg-2 col-md-2 "></div>
                    <!--?  Right content -->
                    <div class="col-xl-8 col-lg-8 col-md-8 ">
                        <!--? New Arrival Start -->
                        <div class="new-arrival new-arrival2">
                            <div class="row" id="productos_tienda">
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-2 col-md-2 "></div>

                    <!-- Modal -->
                    <div class="modal fade bd-example-modal-lg" id="detalles_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div id="contenido_modal">

                                </div>
                                <div class="modal-footer">
                                    <button type="button" id="detalles_agregar_boton" class="genric-btn primary" style="display: block; margin: 0 auto;">Agregar al Carrito</button>
                                </div>
                            </div>
                        </div>
                    </div>
