<div class="row">
    <div>
        <div class="card">
            <div class="card-header">
                <div class="row">
                <div class="col-md-3">
                <h3 class="card-title">Consulta Usuarios</h3>
                </div>
                <div class="col-md-3">
                    <button type="button" id="consultar_productos" class="btn btn-primary">Consultar</button>
                </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table table-striped" id="reporte_productos">
                    <thead>
                        <tr>
                        <th style="width: 10px">ID</th>
                        <th>Descripción</th>
                        <th>ID Tipo Producto</th>
                        <td>ID Marca</td>
                        <td>ID Modelo</td>
                        <td>Precio</td>
                        <th>Imagen</th>
                        <th>Publicado</th>
                        <th>Concepto</th>
                        <td>Estado</td>
                        </tr>
                    </thead>
                    
                </table>
            </div>
            <!-- /.card-body -->
        </div>
            <!-- /.card -->
    </div>
    </div>
</div>