    <!-- ******************************************************************************************* -->
    <div class="hold-transition login-page">
    <div class="login-box">
      <!-- /.login-logo -->
      <div class="card card-outline card-primary">
        <div class="card-header text-center">
          <a class="h1"><b>Admin</b>LTE</a>
        </div>
        <div class="card-body">
          <p class="login-box-msg">Ingrese Usuario y Contraseña, para ingresar al sistema</p>

          <form method="post">
            <div class="input-group mb-3">
              <input type="text" id="usuario" name="usuario" class="form-control" placeholder="Usuario">
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-envelope"></span>
                </div>
              </div>
            </div>
            <div class="input-group mb-3">
              <input type="password" id="clave_acceso" name="clave_acceso" class="form-control" placeholder="Clave de Acceso">
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-lock"></span>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-8">
            
              </div>
              <!-- /.col -->
              <div class="col-4">
                <button type="submit" id="iniciar_sesion" class="btn btn-primary btn-block">Ingresar</button>
              </div>
              <!-- /.col -->
            </div>
          </form>
        </div>
        <!-- /.card-body -->
      </div>
      <div class="row">
        
      </div>
      <!-- /.card -->
    </div>
    </div>
<!-- /.login-box -->
<!-- ******************************************************************************************* -->