          <div class="col-md-10">
            <div class="card card-primary card-outline">
              <div class="card-header">
                <h3 class="card-title">Correo</h3>
              </div>
              <!-- /.card-header -->

              <div class="card-body">
                <div class="form-group">
                  <input class="form-control" name="correo" id="correo" placeholder="Para:">
                </div>
                <div class="form-group">
					<input class="form-control" name="asunto" id="asunto" placeholder="Asunto:">
                </div>
                <div class="form-group">
                    <textarea name="comentario" id="comentario" class="form-control" style="height: 300px">
                      
                    </textarea>
                </div>
                
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <div class="float-right">
                  <button type="button" id="enviar_correo_admin" class="btn btn-primary"><i class="far fa-envelope"></i> Enviar</button>
                </div>
                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> Discard</button>
              </div>
              
              <!-- /.card-footer -->
            </div>
            <!-- /.card -->
          </div>
          
